apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "teamcity.fullname" . }}-agent
  labels:
    app: {{ template "teamcity.name" . }}-agent
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}-agent
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}-agent
        release: {{ .Release.Name }}
    spec:
      volumes:
          - name: agent-data
            {{- if .Values.agent.persistentVolume.enabled }}
            persistentVolumeClaim:
              claimName: s3-dataset
            {{- else }}
            emptyDir: {}
            {{- end }}
      containers:
        - name: {{ template "teamcity.fullname" . }}-agent
          image: {{ .Values.agent.image.repository }}:{{ default "latest" .Values.server.image.version }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
            - name: SERVER_URL
              value: "http://{{ template "teamcity.fullname" . }}:{{ .Values.service.port }}"
          volumeMounts:
            - name:  agent-data
              mountPath: /data/teamcity_agent/conf
          resources:
{{  toYaml .Values.agent.resources | indent 12 }}
{{- with .Values.agent.nodeSelector }}
      nodeSelector:
{{    toYaml . | indent 8 }}
{{- end }}
{{- with .Values.agent.affinity }}
      affinity:
{{    toYaml . | indent 8 }}
{{- end }}
{{- with .Values.agent.tolerations }}
      tolerations:
{{    toYaml . | indent 8 }}
{{- end }}
