{{- if .Values.ingress.enabled -}}
{{-   $serviceName := include "teamcity.fullname" . -}}
{{-   $servicePort := .Values.service.port -}}
{{-   $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{-   if .Values.ingress.labels }}
{{      toYaml .Values.ingress.labels | indent 4 }}
{{-   end}}
{{-   if .Values.ingress.annotations }}
  annotations:
{{-     range $key, $val := .Values.ingress.annotations }}
{{        $key | indent 4 }}: {{ $val | quote }}
{{-     end}}
{{-   end }}
spec:
{{-   if .Values.ingress.defaultBackend.enabled }}
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
{{-   end -}}
{{-   if .Values.ingress.hosts }}
  rules:
{{-     range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{-     end -}}
{{-   end -}}
{{-   if .Values.ingress.tls }}
  tls:
{{      toYaml .Values.ingress.tls | indent 4 }}
{{-   end -}}
{{- end -}}
