{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    component: {{ template "teamcity.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "teamcity.serviceAccountName" . }}
{{- end }}