apiVersion: v1
kind: Service
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{-   range $key, $val := .Values.service.annotations }}
{{      $key | indent 4 }}: {{ $val | quote }}
{{-   end}}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.por
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "teamcity.name" . }}
    # version: {{ .Values.server.image.version }}
    release: {{ .Release.Name }}
