apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: s3-dataset
  namespace: teamcity
spec:
  local:
    type: "COS"
    accessKeyID: "AKIARE4BAT2XIIDXBCME"
    secretAccessKey: "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"
    endpoint: "https://s3.us-east-2.amazonaws.com"
    bucket: "storage-teamcity"
    readonly: "false" #OPTIONAL, default is false
    region: "us-east-2" #OPTIONAL