apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-creds
  namespace: dlf
data:
  accessKeyID: QUtJQVJFNEJBVDJYSUlEWEJDTUU=
  secretAccessKey: Z2QzQzFzamY4T3RxRnYzSEVKUlg5M1V6Qlk4Z243dDlBV2xQNy9BNA==