{{- if .Values.ingress.enabled -}}
{{-   $serviceName := include "teamcity.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{-   if .Values.ingress.labels }}
{{      toYaml .Values.ingress.labels | indent 4 }}
{{-   end}}
{{-   if .Values.ingress.annotations }}
  annotations:
{{-     range $key, $val := .Values.ingress.annotations }}
{{        $key | indent 4 }}: {{ $val | quote }}
{{-     end}}
{{-   end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path  }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
{{- end -}}
