kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.pvc.server.storageClassName }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
mountOptions:
  - debug
volumeBindingMode: Immediate